config/routes.rb
Controlpanel::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/editpw" => "users#edit_password", :as => :editpw
    put "/users/editpw" => "users#update_password", :as => :editpwpost
    get "/users/profile" => "users#profile", :as => :userprofile
  end
  
  resources :apps do
    get 'databases'
    get 'ssh'
    get 'architecture'
    post 'new_ssh_password'
    post 'maximum_web_instances'
    resources :routes do
      get :verify_dns
      post :verify_dns
      post :verify_domain_dns
      get :refresh
    end
    resources :service_instances
    resources :deployments do
      post :commit_staging
      post :cancel_staging
      get :drain_status
    end
    resources :commands
    resources :periodic_tasks
    collection do
      resources :templates, :controller => "app_templates"
    end
  end
  
  resources :domains do
    post 'destroy'
    collection do
      post 'get_or_create'
      get 'list'
    end
    get :verify_dns
    post :verify_dns
  end

  resources :ssl

  namespace 'api' do
    namespace 'cli' do
      namespace 'v1' do
        resources :apps do
          get 'info'
          post 'upload'
          post 'deploy'
          get 'deploy_status'
          post 'set_template'
          resources :commands
          resources :cli_tasks do
            post 'dispatch_task'
            get 'drain_status'
          end
        end
      end
    end
  end

  match "/info" => "api/cli/v1/api#info"

  root :to => "apps#index"
end

app/views/apps/_new_custom.haml
= f.label nil, "Technology:"
%br
- AppTemplate.find(:all, :params => {:template_type => "framework"}).each_with_index do |t, i|
  = render :partial => "new_template", :locals => {:t => t, :i => i}
%br{:style => 'clear: left'}
%br
= label_tag :database_service, "Database:"
%br
- {:pg => 'PostgreSQL', :mysql => 'MySQL'}.each_pair.each_with_index do |p,i|
  %div.radio#database_service
    = radio_button_tag :database_service, p[0], i==0 ? true : false, :id => "database_service_#{p[0]}"
    %label{:for => "database_service_#{p[0]}"}
      = image_tag "/images/services/#{p[1].downcase}.png"
      = p[1]

app/views/apps/_new_template.haml
%div.radio#template_id
  = radio_button_tag :template_id, t.id, i==0 ? true : false, :id => "template_id_#{t.id}"
  %label{:for => "template_id_#{t.id}"}
    = image_tag t.icon_url
    = t.name.sub(' / ','<br />').html_safe

app/views/apps/_show.haml
%li.app.with-screenshot
  %div.with-screenshot
    = link_to image_tag(app.screenshot_url), app.default_route
    - if app.template.icon_url
      = link_to image_tag(app.template.icon_url, :class => 'icon'), app.default_route
  .name
    = app.name
  .location
    .url
      %small>
        %a{:href=>app.default_route}
          = app.default_route

  .stats
    /Services:
    - app.service_instances.each do |service_instance|
      %img{src: "/images/services/#{service_instance.service.name.downcase}.png", title: service_instance.service.name}
    /
      %br>
      10 Instances
      %br>
      ø 3.5 ms Latency
      %br>
      n-Redundancy
  %ul.actions
    %li.update= link_to 'Upload Sourcecode', new_app_deployment_url(app)
    %li.locations= link_to 'Locations', app_routes_url(app)
    %li.databases= link_to 'Databases', app_databases_url(app)
    %li.architecture= link_to 'Architecture', app_architecture_url(app)
    %li.commands= link_to 'Cronjobs', app_commands_url(app)
    //%li.plugins= link_to 'Add-ons', '#'
    //%li.stats= link_to 'Stats', '#'

app/views/apps/_show_mini.haml
%li.app.mini{:class => app.screenshot_url ? ' with-screenshot' : ''}
  - if app.screenshot_url
    %div{:class => app.screenshot_url ? ' with-screenshot' : '' , :style => ("background-image: url(#{app.screenshot_url})" if app.screenshot_url)}
      - if app.template.icon_url
        = image_tag(app.template.icon_url, :class => 'icon')
  - else
    = app.template.name
  .name
    = app.name

app/views/apps/architecture.haml
%h2= '%s: Cloud Architecture' % @app.name

.service_overview
  .visitors.block
    %img{:src => "/images/visitors.png"}
    %br>
    Visitors
  .arrow.block
  .services.block
    - Service.find(:all, :params => {:type => "HttpGateway"}).each do |http_gateway|
      .service{:id=>'service-lb'}
        Load Balancer
        .detail
          nginx 1.0.X
  .arrow.block
  .services.block{:style => 'min-height: 51px;'}
    %div{:style=>'position: absolute; left: 180px;'}
      .replace_here.serviceoverride#service-webinstances
        #replace_here
          .spinner
            %input{:type=>:text,:class=>'spinner',:name=>'maximum_web_instances',:value=>@app.maximum_web_instances,:size=>2,:style=>"display: inline; margin: 0; padding: 0; border: none; width: 1.5em; height: 1.4em !important;font-size: 1.7em; line-height: 1.4em; text-align: center", 'data-autosubmit' => app_maximum_web_instances_path(@app) + ' #replace_here'}
            .detail{:style=>'font-size: .65em; line-height: 1em;'} instances
            .updown
              .up
                +
              .down
                \-
    - if @app.active_deployment
      - @app.active_deployment.deployment_installs.map {|install| install.service }.each do |app_host|
        .service{:id => 'service-webserver'}
          Web Server
          .detail
            = @app.template.name
      - if @app.active_deployment.deployment_installs.length == 0
        .service{:id => 'service-webserver'}
          Web Server
          .detail
            = @app.template.name
    - else
      .no_deployment
        Web Server not active
        %br
        = link_to "Upload sourcecode", new_app_deployment_url(@app)

  .arrow.double.block
  .services.block.databases
    - @app.service_instances.each do |service_instance|
      .service{:id => "service-#{service_instance.id}"}
        = service_instance.service.name

  .descriptions
    .service.hint.show
      Click on a server to show its configuration, availability and scaling information.
    - @app.service_instances.each do |service_instance|
      .service{:for => "service-#{service_instance.id}"}
        %h3
          = service_instance.service.description
        != BlueCloth.new(service_instance.service.info || '').to_html
        %ul{:style => "margin-bottom: 0"}
          %li
            %strong Hostname:
            127.0.0.1
          - if service_instance.connectiondata.attributes['username']
            %li
              %strong Username:
              = service_instance.connectiondata.attributes['username']
          - if service_instance.connectiondata.attributes['password']
            %li
              %strong Password:
              = service_instance.connectiondata.attributes['password']
          - if service_instance.connectiondata.attributes['database']
            %li
              %strong Database:
              = service_instance.connectiondata.attributes['database']
    .service{:for => 'service-webserver'}
      %h3
        = @app.template.name
      This is your application webserver, running your uploaded sourcecode.
    .service{:for => 'service-lb'}
      %h3
        Load Balancer
      %ul
        %li
          %strong IP Address:
          = Service.find(:all, :params => {:type => "HttpGateway"}).first.server.external_ip
        %li
          %strong Software:
          nginx 1.0.X
        %li
          %strong Redundant:
          No
      The load balancer distributes requests across multiple web servers and takes care of slow clients and uploads.
    .service{:for=>'service-webinstances'}
      %h3
        Web Instances Setting
      %p
        Create multiple instances for scaling purposes.
      %p
        Maximum Number for your account:
        = User.to_adapter.get(@app.user_id).maximum_web_instances_allowed + 1 - App.to_adapter.find_all(:user_id => @app.user_id).select{|x| x.id != @app.id}.map{|x| x.maximum_web_instances - 1}.sum

app/views/apps/databases.haml
%h2= '%s: Databases' % @app.name

.databases
  %table
    %tr
      %th
      %th Host
      %th Port
      %th Database Name
      %th Username
      %th Password
    - @service_instances.each do |service_instance|
      - cd = service_instance.connectiondata.attributes
      %tr
        %th.name= service_instance.service.name
        %td 127.0.0.1
        %td= cd['default_local_port']
        %td{:class => cd['database'] ? '' : 'empty'}= cd['database']
        %td{:class => cd['username'] ? '' : 'empty'}= cd['username']
        %td{:class => cd['password'] ? '' : 'empty'}= cd['password']
%br
This is for connections from your application running inside the cloud.
%br
External database access is currently not available.

app/views/apps/index.haml
%ul.installed-apps
  - @apps.each do |app|
    = render :partial => 'show', :locals => {:app => app}
  %li{:class => (@apps.count == 0 ? "new_app_btn new_first_app_btn" : "new_app_btn")}
    %a{:href => new_app_path}
      Add Website

app/views/apps/new.haml
%h2 Add new website

= form_for @app do |f|
  #tabs
    %ul
      %li
        %a{:href => "#tabs-1"} Application Templates
      %li
        %a{:href => "#tabs-2"} Custom Application
    #tabs-1
      - AppTemplate.find(:all, :params => {:template_type => "application"}).each_with_index do |t, i|
        = render :partial => "new_template", :locals => {:t => t, :i => i}
    #tabs-2
      = render :partial => "new_custom", :locals => {:f => f}
  %p.aside
    You can configure website address and other settings later on.
  %br
  = f.submit "Continue"

:javascript
  $("#tabs").tabs();

app/views/apps/ssh.haml
.ssh
  To connect to your App via SSH, use this:
  %br
  %br
    %code= 'ssh app%d@%s' % [@app.id, CLOUD_CONFIG['apps.ssh.gateway.host']]
  %br
    Please note that local changes will be thrown away.
  %br
  %span#new_password  
    = button_to 'Request new password', app_new_ssh_password_path(@app), :method=>'post', :remote => true, :disable_with => 'Loading...'