config/routes.rb
Controlpanel::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/editpw" => "users#edit_password", :as => :editpw
    put "/users/editpw" => "users#update_password", :as => :editpwpost
    get "/users/profile" => "users#profile", :as => :userprofile
  end
  
  resources :apps do
    get 'databases'
    get 'ssh'
    get 'architecture'
    post 'new_ssh_password'
    post 'maximum_web_instances'
    resources :routes do
      get :verify_dns
      post :verify_dns
      post :verify_domain_dns
      get :refresh
    end
    resources :service_instances
    resources :deployments do
      post :commit_staging
      post :cancel_staging
      get :drain_status
    end
    resources :commands
    resources :periodic_tasks
    collection do
      resources :templates, :controller => "app_templates"
    end
  end
  
  resources :domains do
    post 'destroy'
    collection do
      post 'get_or_create'
      get 'list'
    end
    get :verify_dns
    post :verify_dns
  end

  resources :ssl

  namespace 'api' do
    namespace 'cli' do
      namespace 'v1' do
        resources :apps do
          get 'info'
          post 'upload'
          post 'deploy'
          get 'deploy_status'
          post 'set_template'
          resources :commands
          resources :cli_tasks do
            post 'dispatch_task'
            get 'drain_status'
          end
        end
      end
    end
  end

  match "/info" => "api/cli/v1/api#info"

  root :to => "apps#index"
end

app/models/route.rb
class Route < ActiveResource::Base
  extend ActiveSupport::Memoizable
  self.site = HS_CONFIG['cc_api_host']
  self.prefix = '/api/v1/apps/:app_name/'
  self.user = HS_CONFIG['cc_api_user']
  self.password = HS_CONFIG['cc_api_password']

  schema do
    string 'subdomain'
    integer 'domain_id'
  end
  
  def app_name; prefix_options[:app_name]; end
  def app; App.find(app_name); end
  memoize :app
  
  def hostname
    (subdomain.blank? ? '' : (subdomain + '.')) + domain.name
  end
  def url
    hostname
  end
  def dns_state
    if self.dns_verify_last_successful
      return [:ok, 'Your App can be reached at this location.']
    end
    if not self.domain.verified
      return [:error, 'We will not serve requests to this location your ownership of this domain is verified.']
    end
    return [:warning, 'We will serve requests to this location, but the DNS settings do not seem to be correct.']
  end
  memoize :dns_state

  def ssl_state
    if self.key_material_id
      return [:ok, 'SSL Configured.']
    end
    return [:off, 'No key configured for SSL.']
  end
  memoize :ssl_state

  def domain
    Domain.to_adapter.find_first :id => domain_id
  end
  memoize :domain

  def verify_dns!
    self.attributes = JSON.parse(post(:verify).body)
  end

  def expected_dns
    @_expected_dns ||= get(:expected_dns)
  end

  def <=>(other)
    default_route = self.app.routes[0]
    if self == default_route
      return -1
    end
    if other == default_route
      return 1
    end

    default_route_domain_name = default_route.domain.name
    this_domain = self.domain.name
    other_domain = other.domain.name
    if(this_domain != other_domain)
      if this_domain == default_route_domain_name
	return -1
      end
      if other_domain == default_route_domain_name
	return 1
      end
      this_domain <=> other_domain
    else
      (self.subdomain||'') <=> (other.subdomain||'')
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  #before_filter :login_required
  before_filter :load_app
  
  def create
    params[:route].delete(:redirect_target_id) if params[:route][:type] == 'show'
    @domain = Domain.find(:all, :params => {:user_id => current_user.id}).select{|x| x.name==params[:domain]}[0]
    if not @domain
      @domain = Domain.create(:user_id => current_user.id, :name => params[:domain])
    end
    if @domain and @domain.id
      @route = Route.create(params[:route].merge(:app_name => @app.name, :domain_id => @domain.id))
    end
    render :partial => 'list-item', :locals => {:route => @route||nil, :domain => @domain, :created => true}
  end
  
  def destroy
    @route = Route.find(params[:id], :params => {:app_name => @app.name})
    @route.destroy
    render :text => ''
  end

  def verify_dns
    @route = Route.find(params[:route_id], :params => {:app_name => @app.name})
    if request.get?
      render :partial => 'verify'
    else
      @route.verify_dns!
      @route_result = @route
      render :partial => 'verify'
    end
  end

  def verify_domain_dns
    @route = Route.find(params[:route_id], :params => {:app_name => @app.name})
    if request.get?
      render :partial => 'verify'
    else
      @route.domain.verify_dns!
      @route = Route.find(params[:route_id], :params => {:app_name => @app.name})
      @domain_result = @route.domain
      render :partial => 'verify'
    end
  end

  def refresh
    @app = App.to_adapter.find_first :name => params[:app_id]
    @route = Route.to_adapter.find_first :id => params[:route_id], :app_name => params[:app_id]
    @is_refresh = true
    render :partial => 'list-item', :locals => {:route => @route, :domain => @route.domain}
  end
end

app/views/routes/_list-item.haml
- if not (route and route.id) and not (domain and domain.id)
  %li.location
    %label Failed
    Invalid Domain!
- else
  %li.location{'data-location-id' => route.id, 'data-refresh-url' => app_route_refresh_path(route.app, route), 'data-domain' => route.domain_id ? route.domain.name : ''}
    %div{'id' => @is_refresh ? 'refresh' : nil}
      - if route.errors.length>0
        %label Failed
      - else
      - if route.domain
        = render :partial => 'routes/url', :locals => {:route => route}
      - if route.errors.length==0
        = link_to 'Delete', [route.app, route], :method => :delete, :remote => :true, :class => 'delete'
        %span{:class => "ssl ssl_#{route.ssl_state[0]}", :title => route.ssl_state[1]} SSL
        = link_to 'DNS', app_route_verify_dns_path(route.app, route), :remote => true, :class => "dns dns_#{route.dns_state[0]}", :title => route.dns_state[1]
        - if defined? created
          .dnsintro
            DNS settings here:
      - else
        - route.errors.each do |k,v|
          = k.to_s.sub(/_id/,'')
          = v

app/views/routes/_url.haml
.url
  %a{:href => url||'http://'+route.url}
    %small>
    = url || 'http://'+ route.url

app/views/routes/_verify.haml
.location_verify
  %p= @route.dns_state[1]

  - if @route.dns_state[0] != :ok
    %p To fix this, please set your DNS configuration to:

  - cname = @route.expected_dns.keys.include? 'cname'
  %table
    %tr.copypaste
      %th Name
      %th Type
      %th Content
    %tr.copypaste
      %td= @route.hostname
      %td= (cname ? 'CNAME' : 'A')
      %td= @route.expected_dns[cname ? 'cname' : 'a' ][0]
    %tr.buttons
      %td
        = button_to 'Recheck', app_route_verify_dns_path(@route.app, @route), :remote=>true
      %td.aside{:colspan=>2}
        Last Check:
        = @route.dns_verify_last_at or 'Never'
    - if @route_result
      %tr.route_result
        %td &nbsp;
        %td{:colspan=>2}
          - if @route.dns_verify_last_successful
            Congrats, this location is properly set up!
          - else
            Sorry, the validation failed at this time.
            %br>
            This might be the fault of your provider, try again in a few minutes!
            %br>
            %a.d{:onclick=>'$(".route_result .details").show();return false;'} Show Details
            .details{:style => 'display: none;'}
              %pre= @route_result.dns_verify_last_log

  - if not @route.domain.verified or @domain_result
    %br>
    - if not @domain_result
      %br>
      %br>
      %p.aside
        %a.d{:href=>'', :onclick=>'$("#domain_verify").show(); return false;'} I do not want to point my DNS record to the new site yet
    #domain_verify{:style=> ( @domain_result ? '' : 'display: none;' ) }
      - if @route.domain.verified
        %p
          Congrats, the domain is now verified!
      - else
        %p
          If you do not want to do this yet but need us to serve the app on this location for testing purposes,
          you can verify your domain ownership seperately by creating the following DNS entry:
        %table
          %tr.copypaste
            %th Name
            %th Type
            %th Content
          %tr.copypaste
            %td= "#{@route.domain.verification_code}.#{@route.domain.name}"
            %td= 'CNAME'
            %td= CLOUD_CONFIG['cloud.domain.name']
          %tr.buttons
            %td
              = button_to 'Recheck', app_route_verify_domain_dns_path(@route.app, @route), :remote => true
            %td.aside{:colspan=>2}
              Last Check:
              = @route.domain.dns_verify_last_at or 'Never'
          - if @domain_result
            %tr.domain_result
              %td &nbsp;
              %td{:colspan=>2}
                Sorry, the validation failed at this time.
                %br>
                This might be the fault of your provider, try again in a few minutes!
                %br>
                %a.d{:onclick=>'$(".domain_result .details").show();return false;',:href=>''} Show Details
                .details{:style => 'display: none;'}
                  %pre= @domain_result.dns_verify_last_log

app/views/routes/index.haml
%h2= '%s: Locations' % @app.name

.settings
  %ul.locations
    %li.location
      .url
        %small>
          = @app.builtin_route
    = render :partial => 'routes/list-item', :collection => @app.routes.sort, :as => :route
  %div#add_location
    %hr>
    = form_for [@app, Route.new(:app_name => @app.name)], :remote => true do |f|  
      .location
        %p.proxy.url
          http://
          = f.text_field :subdomain, :size => 8, :title=>"subdomain"
          \.
          <input type="text" name="domain" value="" id="route_domain_name" size=10 title="example.com" />
          \/
        .actions
          .verify
            we don't know if this domain is yours. please
            = button_to_function 'Verify it',"", :id => 'verify_domain'
          .errors
          = f.submit 'Add'
          %p#route_domain_unknown We will have to verify your ownership of this domain after you have added it.