config/routes.rb
Controlpanel::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/editpw" => "users#edit_password", :as => :editpw
    put "/users/editpw" => "users#update_password", :as => :editpwpost
    get "/users/profile" => "users#profile", :as => :userprofile
  end
  
  resources :apps do
    get 'databases'
    get 'ssh'
    get 'architecture'
    post 'new_ssh_password'
    post 'maximum_web_instances'
    resources :routes do
      get :verify_dns
      post :verify_dns
      post :verify_domain_dns
      get :refresh
    end
    resources :service_instances
    resources :deployments do
      post :commit_staging
      post :cancel_staging
      get :drain_status
    end
    resources :commands
    resources :periodic_tasks
    collection do
      resources :templates, :controller => "app_templates"
    end
  end
  
  resources :domains do
    post 'destroy'
    collection do
      post 'get_or_create'
      get 'list'
    end
    get :verify_dns
    post :verify_dns
  end

  resources :ssl

  namespace 'api' do
    namespace 'cli' do
      namespace 'v1' do
        resources :apps do
          get 'info'
          post 'upload'
          post 'deploy'
          get 'deploy_status'
          post 'set_template'
          resources :commands
          resources :cli_tasks do
            post 'dispatch_task'
            get 'drain_status'
          end
        end
      end
    end
  end

  match "/info" => "api/cli/v1/api#info"

  root :to => "apps#index"
end

app/models/deployment.rb
class Deployment < ActiveResource::Base
  self.site = HS_CONFIG['cc_api_host']
  self.prefix = '/api/v1/apps/:app_name/'
  self.user = HS_CONFIG['cc_api_user']
  self.password = HS_CONFIG['cc_api_password']

  def app_name; prefix_options[:app_name]; end
  def app; App.find(app_name); end

  def deploy!
    post(:deploy, :id => self.id)
  end
  def commit_staging!
    body = post(:commit_staging, :id => self.id).body.to_s
    Rails.logger.warn("resp body: #{body.inspect}")
    doc = REXML::Document.new body
    new_deployment_id = doc.elements["deployment/new-deployment-id"].text.to_i
    Deployment.find(new_deployment_id, :params => {:app_name => app_name })
  end
  def undeploy!
    post(:undeploy, :id => self.id)
  end

  def drain_status!
    doc = REXML::Document.new post(:drain_status, :id => self.id).body.to_s
    resp = {:message => doc.elements["deployment/message"].text}
    logs = doc.elements["deployment/logs"].text
    resp[:logs] = logs if logs
    resp
  end
end

app/controllers/deployments_controller.rb
class DeploymentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_app
  before_filter :load_deployment, :except => [:new, :create, :index]

  def new
    if deployment = @app.staging_deployment || Deployment.find(:all, :params => {:app_name => @app.name, :state => :working}).first
      redirect_to [@app, deployment]
      return
    end
    @deployment_upload = Deployment.new :app_name => @app.name, :source => :upload
    @deployment_interactive = Deployment.new :app_name => @app.name, :source => :interactive
  end

  def create
    @deployment = Deployment.new :app_name => @app.name
    if params[:deployment][:source] == 'interactive'
      @deployment.source = :interactive
      @deployment.envtype = :staging
      @deployment.code_token = @app.active_deployment.code_token rescue 'empty'
    else
      @deployment.source = :upload
      unless code = params[:deployment][:code] rescue nil
        redirect_to new_app_deployment_path, :alert => "Please select a zip file to upload"
        return
      end
      archive = Codearchive.new @app, code.tempfile
      archive.save!
      code.tempfile.close!
      @deployment.code_token = archive.code_token
    end
    @deployment.save!
    @deployment.deploy!
    redirect_to [@app, @deployment]
  end

  def commit_staging
    if @deployment.envtype == 'staging'
      new_deployment = @deployment.commit_staging!
      redirect_to [@app, new_deployment]
    else
      raise "Wrong deployment type"
    end
  end

  def cancel_staging
    if @deployment.envtype == 'staging'
      @deployment.undeploy!
    else
      raise "Wrong deployment type"
    end
    redirect_to new_app_deployment_path
  end

  def show
  end

  def drain_status
    respond_to do |format|
      format.json { render :json => @deployment.drain_status! }
    end
  end

  def destroy
    @deployment.state = :removed
    @deployment.save
    redirect_to new_app_deployment_path
  end

protected
  def load_deployment
    @deployment = Deployment.find(params[:deployment_id] || params[:id], :params => {:app_name => @app.name})
  end
end

app/views/deployments/new.haml
%h2= '%s: Upload Sourcecode' % @app.name

#deployment
  %ul.nav
    %li.upload
      = link_to "Upload Zip File", "#source-upload"
    %li.interactive
      = link_to "SFTP (SSH)", "#source-interactive"
    %li.cli
      = link_to "Commandline Deploy Tool", "#source-cli"
  #source-upload
    - if @app.active_deployment && @app.active_deployment.source == 'interactive'
      %p.warning
        The current deployment was created via SFTP/SSH.
        %br>
        Deploying this way, you will lose all code changes you made earlier!
    = form_for [@app, @deployment_upload], :html => {:multipart => true} do |f|
      = f.hidden_field :source
      %p
        Please create a .zip file containing your website's sourcecode &amp; select it here:
      %br
      %p#upload_selector
        = f.file_field :code
      #uploading{:style => "display: none"}
        #progress.bar
          #progressbar
      = f.submit "Upload now"
  #source-interactive
    %div{:style => 'float: left;'}
      = form_for [@app, @deployment_interactive] do |f|
        = f.hidden_field :source
        = f.submit "Enable"
    %p{:style => 'margin-left: 7em; line-height: 2em;'}
      This method allows you to upload your application's sourcecode using any SFTP client.
    %p.btw
      You will also have the chance to try out your application on a test address.
      %br>
      This is great for installing many PHP-based web applications that require you to click through an installer or setup wizard.
    %p.btw
      Advanced users can also use this to inspect the runtime environment using SSH.
  #source-cli
    - if @app.active_deployment && @app.active_deployment.source == 'interactive'
      %p.warning
        The current deployment was created via SFTP/SSH.
        %br>
        Deploying this way, you will lose all code changes you made earlier!
    %p
      1. Install the deploy commandline tool (for OSX and Linux - requires Rubygems)
    .upload-commands
      gem install hsdeploy
    %p
      2. Create the target (only necessary once)
    .upload-commands
      = "hsdeploy add production %s" % @app.cli_api_app_name
    %p
      3. Deploy
    .upload-commands
      hsdeploy production

    %p
      After the upload finished, you can
      %a{:href => @app.default_route} visit the website
      to test it.

:javascript
  var active_deployment_source = "#{h @app.active_deployment.source rescue ""}";
  $('#deployment').tabs();
  if (active_deployment_source != "") {
    $('#deployment').tabs("select", "#source-" + active_deployment_source);
  }
  $('#source-upload #deployment_submit')[0].disabled = false; /* Partial refresh sometimes keeps disabled state */
  $('#source-upload form#new_deployment').uploadProgress({
    start: function() {
      $('#source-upload #deployment_submit')[0].value = "Uploading...";
      $('#source-upload #deployment_submit')[0].disabled = true;
      $('#upload_selector').hide();
      $('#uploading').show();
    },
    error: function() {
      $('#source-upload #deployment_submit')[0].value = "Start deployment";
      $('#source-upload #deployment_submit')[0].disabled = false;
      $('#progressbar').css('width', 0);
      $('#upload_selector').show();
      $('#uploading').hide();
    }
  });

app/views/deployments/show.haml
- if @deployment.state == 'success'
  #deployment_state
    - if @deployment.envtype == 'staging'
      %h2= '%s: SFTP Upload (SSH Access)' % @app.name
      %table.deployment_details
        %tr
          %th
            Host:
          %td
            = @deployment.ssh_hostname
        %tr
          %th
            Username:
          %td
            = @deployment.ssh_username
        %tr
          %th
            Password:
          %td
            %span#new_password
              = button_to 'Request new password', app_new_ssh_password_path(@app), :method=>'post', :remote => true, :disable_with => 'Loading...'

      %p
        To test your application, go to
        %br>
        %code
          = link_to @app.builtin_route_staging, @app.builtin_route_staging, :target => '_blank'
      %table.buttons
        %tr
          %td
            %span.prose
              when you're confident that your app works, 
            = button_to 'Save changes', app_deployment_commit_staging_path(@app, @deployment), :method=>'post', :disable_with => 'Loading...'
          %td.cancel
            %span.prose
              if you prefer to start over
              %br>
              or want to upload sourcecode using a different method
            = button_to 'Cancel', app_deployment_cancel_staging_path(@app, @deployment), :method=>'post', :disable_with => 'Loading...', :class => 'cancel'
    - else
      %h2= "%s: Deployment Successful!" % @app.name
      %table.deployment_details
      %p
        You can now visit the website at:
        = link_to @app.default_route, @app.default_route, :target => '_blank'
- elsif @deployment.state == 'failure'
  #deployment_state
    %h2= "%s: Deployment Failed" % @app.name
    %p
      Please contact the support team and mention
      %strong deployment #{@deployment.id}.
    %p
      = link_to 'Back to "Upload Sourcecode"', new_app_deployment_path(@deployment.app)
- else
  - if @deployment.envtype == 'staging'
    %h2= "%s: Preparing SFTP (SSH) environment..." % @app.name
  - else
    %h2= "%s: Deploying..." % @app.name
  #deployment_state.working
    %h2 Please wait...
  
  :javascript
    Controlpanel.Deployment.drain_status('#{app_deployment_drain_status_path(@app, @deployment)}');

#deployment_logs{:class => @deployment.envtype}
  = (current_user.is_admin ? @deployment.log_private : @deployment.log).to_s.gsub("\n", "<br />").html_safe

:javascript
  $('#deployment_logs').scrollTop(1000000);