config/routes.rb
Controlpanel::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/editpw" => "users#edit_password", :as => :editpw
    put "/users/editpw" => "users#update_password", :as => :editpwpost
    get "/users/profile" => "users#profile", :as => :userprofile
  end
  
  resources :apps do
    get 'databases'
    get 'ssh'
    get 'architecture'
    post 'new_ssh_password'
    post 'maximum_web_instances'
    resources :routes do
      get :verify_dns
      post :verify_dns
      post :verify_domain_dns
      get :refresh
    end
    resources :service_instances
    resources :deployments do
      post :commit_staging
      post :cancel_staging
      get :drain_status
    end
    resources :commands
    resources :periodic_tasks
    collection do
      resources :templates, :controller => "app_templates"
    end
  end
  
  resources :domains do
    post 'destroy'
    collection do
      post 'get_or_create'
      get 'list'
    end
    get :verify_dns
    post :verify_dns
  end

  resources :ssl

  namespace 'api' do
    namespace 'cli' do
      namespace 'v1' do
        resources :apps do
          get 'info'
          post 'upload'
          post 'deploy'
          get 'deploy_status'
          post 'set_template'
          resources :commands
          resources :cli_tasks do
            post 'dispatch_task'
            get 'drain_status'
          end
        end
      end
    end
  end

  match "/info" => "api/cli/v1/api#info"

  root :to => "apps#index"
end

app/models/command.rb
class Command < ActiveResource::Base
  self.site = HS_CONFIG['cc_api_host']
  self.prefix = '/api/v1/apps/:app_name/'
  self.user = HS_CONFIG['cc_api_user']
  self.password = HS_CONFIG['cc_api_password']

  schema do
    string 'name'
    string 'command'
  end

  def app_name; prefix_options[:app_name]; end
  def app; App.find(app_name); end

  def as_json(opts = nil)
    opts ||= {}
    opts[:except] = [opts[:except]].flatten.compact + [:updated_at, :created_at, :app_id]
    super(opts)
  end

  protected
  def validate
    errors.add("command", "must be String") unless command.kind_of?(String)
    errors.add("name", "must be String") unless name.kind_of?(String)
  end
end

app/controllers/api/cli/v1/commands_controller.rb
class Api::Cli::V1::CommandsController < Api::Cli::V1::ApiController
  before_filter :auth_required
  before_filter :app_for_user
  before_filter :find_command, :except => [:index, :create]
  respond_to :json

  def app_for_user
    @app = App.find(params[:app_id])
    raise "Permission denied" unless @app and @app.user_id == @current_user.id
  end

  def index
    respond_with @app.commands
  end

  def create
    @command = Command.create(
                              :app_name => @app.name,
                              :source => :cli,
                              :name => params[:command][:name],
                              :command => params[:command][:command],
                              )
    respond_with :api, :cli, :v1, @app, @command, :status => :created
  end

  def show
    respond_with :api, :cli, :v1, @app, @command
  end

  def update
    return head :forbidden if @command.source.to_s != "cli"
    if updates = params[:command]
      @command.name = updates[:name] unless updates[:name].nil?
      @command.command = updates[:command] unless updates[:command].nil?
      @command.save
    end
    respond_with(:api, :cli, :v1, @app, @command)
  end

  def destroy
    return head :forbidden if @command.source.to_s != "cli"
    @command.destroy
    respond_with(:api, :cli, :v1, @app, @command)
  end

  private
  def find_command
    @command = Command.find(params[:id], :params => {:app_name => params[:app_id]})
    raise "Permission denied" unless @command.app.id == @app.id
  end

end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_filter :login_required
  before_filter :load_app

  def index
    @commands = Command.to_adapter.find_all :app_name => @app.name
    @periodic_tasks = PeriodicTask.to_adapter.find_all(:app_name => @app.name)

    @c = Command.new :app_name => @app.name if not @c or @c.id
    @cs = {}
    @commands.each{|c| @cs[c] = @periodic_tasks.select{|t| t.command_id == c.id}}
  end

  def create
    @c = Command.to_adapter.create! params[:command].merge({:source => :web, :app_name => @app.name})
    @periodic_task = PeriodicTask.to_adapter.create! params[:periodic_task].merge(:app_name => @app.name,:command_id => @c.id,:enabled=>true)
    index()
    render :index
  end

  def update
    @c = Command.to_adapter.find_first :app_name => @app.name, :id => params[:id]
    @c.command = params[:command]
    @c.save

    render :text => 'ok'
  end

  def destroy
    @c = Command.to_adapter.find_first :app_name => @app.name, :id => params[:id]
    @c.destroy
    render :json => 'ok'
  end
end

app/views/commands/index.haml
%h2= '%s: Cronjobs' % @app.name

.commands{:class => @cs.empty? ? 'empty' : ''}
  - if @cs.empty?
    %h2 No jobs defined

  .note
    Jobs may start up to 30min later than specified, due to load distribution

  - @cs.each do |c,ts|
    .command
      .meta
        %h2
          %span.name
            = c.name
          - if c.source == 'web'
            = link_to 'Delete', [@app, c], :method => :delete, :remote => :true, :class => 'delete command'
        .cmd
          = text_field_tag 'command', c.command, 'data-submit' => app_command_path(@app,c), 'class' => 'edit-inline display command noclear'
      .state
        .last-run
          Last Run:
          Unknown
        %br
        = button_to 'Logs', '/TBD', :disabled => 'disabled', :class => 'logs'
        = button_to 'Run Now', '/TBD', :disabled => 'disabled', :class => 'run_now'
      %div.tbl{:style=>'clear:left;'}
        %div.tr.h
          %div.t Scheduled for
          %div.t Start after
          %div.t Enabled
          %div.clr
        - ts.each do |t|
          = render :partial => 'periodic_tasks/show', :locals => {:t => t}
        = form_for PeriodicTask.new, :url => app_periodic_tasks_path(@app.name), :method => :put, :as => :periodic_task, :html => {:class => 'tr append_before','data-remote-append' => true}, :remote => true  do |f|
          %div.t
            = hidden_field_tag 'periodic_task[command_id]', c.id
            = hidden_field_tag 'periodic_task[enabled]', true
            %select{:name=>'periodic_task[interval]'}
              - PeriodicTask.supported_intervals(@app.name).each do |si|
                %option{:value => si}= si
          %div.t
            = select_tag 'periodic_task[start_hour]', (0..23).map{|x| "<option value='%02d'>%02d:00</option>" % [x,x]}.join('').html_safe
          %div.t= f.submit "New"
          %div.clr
  %div.info
    %small Commands that you have defined in your Procfile will also show up here.
  %div.newbtn.add
    %button{:onclick => '$(this).parent().siblings(".new").show(); $(this).hide();'} Create new Command
  %div.new
    %h2 Add Command
    .note
      Commands will run in the <code>/app/code</code> working directory
    %br{:style => 'clear:left'}
    = form_for @c, :url => app_commands_path(@app.name) do |f|
      = f.label :command, "Command", :style => "display:block;"
      = f.text_field :command, :style => "font-family: monospace; min-width: 400px;"
      %br>
      %small{:style=>'font-family: monospace'} Ex: rake job:export_csv
      = @c.errors[:command].join('')
      %br>
      %br>
      = f.label :interval, "Scheduled for"
      = f.label :interval, "Start at", :style => 'position: absolute; left: 120px;'
      %br>
      %select{:name=>'periodic_task[interval]'}
        - PeriodicTask.supported_intervals(@app.name).each do |si|
          %option{:value => si}= si
      = select_tag 'periodic_task[start_hour]', (0..23).map{|x| "<option value='%02d'>%02d:00</option>" % [x,x]}.join('').html_safe, :style => 'position: absolute; left: 120px;'
      %br>
      %br>
      = f.submit "Create"